
name: Deploy to Dev
'on':
  push:
    branches:
      - staging
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
            node-version: 12
      - run: npm ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VPN_WEBSITE_DEV_87FE5 }}'
          channelId: live
          projectId: vpn-website-dev-87fe5
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
